export default [
    {
        id: 1,
        title: 'Headphones',
        description: 'Noise cancelling headphones, perfect for loud commutes',
        url: 'headphones.jpg',
        price: 149.99,
        inStock: true,
    },   
    {
        id: 2,
        title: 'Sunglasses',
        description: 'Stylish and comfortable',
        url: 'sunglasses.jpg',
        price: 59.99,
        inStock: true,
    },   
    {
        id: 3,
        title: 'Vintage car',
        description: 'Straight from the 1960s',
        url: 'car.jpg',
        price: 7500.00,
        inStock: false,
    },   
    {
        id: 4,
        title: 'Plant',
        description: 'Freshen up your home',
        url: 'plant.jpg',
        price: 24.49,
        inStock: true,
    },   
    {
        id: 5,
        title: 'Drink bottle',
        description: 'Sleek and ergonomic',
        url: 'bottle.jpg',
        price: 20.99,
        inStock: false,
    },   
    {
        id: 6,
        title: 'Backpack',
        description: 'Made with the finest materials',
        url: 'bag.jpg',
        price: 55.00,
        inStock: true,
    },
    {
        id: 7,
        title: 'Watch',
        description: 'Modern and luxurious',
        url: 'watch.jpg',
        price: 199.99,
        inStock: true,
    },
    {
        id: 8,
        title: 'Bicycle',
        description: 'Perfect for city commutes or countryside adventures',
        url: 'bike.jpg',
        price: 330.00,
        inStock: false,
    },
    {
        id: 9,
        title: 'Running shoes',
        description: 'Providing ultimate comfort for your run',
        url: 'shoes.jpg',
        price: 59.49,
        inStock: true,
    }, 
    {
        id: 10,
        title: 'Drone',
        description: 'The possibilies are endless',
        url: 'drone.jpg',
        price: 1099.99,
        inStock: true,
    } 
]